# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignUp.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 568)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 118))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.registration = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.registration.setFont(font)
        self.registration.setAlignment(QtCore.Qt.AlignCenter)
        self.registration.setWordWrap(False)
        self.registration.setObjectName("registration")
        self.verticalLayout.addWidget(self.registration)
        self.line_login = QtWidgets.QLineEdit(self.centralwidget)
        self.line_login.setGeometry(QtCore.QRect(210, 180, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_login.setFont(font)
        self.line_login.setObjectName("line_login")
        self.line_password = QtWidgets.QLineEdit(self.centralwidget)
        self.line_password.setGeometry(QtCore.QRect(210, 240, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_password.setFont(font)
        self.line_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_password.setObjectName("line_password")
        self.login = QtWidgets.QLabel(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(210, 155, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.login.setFont(font)
        self.login.setObjectName("login")
        self.password = QtWidgets.QLabel(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(210, 215, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.signUp = QtWidgets.QPushButton(self.centralwidget)
        self.signUp.setGeometry(QtCore.QRect(210, 330, 371, 23))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.signUp.setFont(font)
        self.signUp.setObjectName("signUp")
        self.password_repeat = QtWidgets.QLabel(self.centralwidget)
        self.password_repeat.setGeometry(QtCore.QRect(210, 275, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.password_repeat.setFont(font)
        self.password_repeat.setObjectName("password_repeat")
        self.line_password_repeat = QtWidgets.QLineEdit(self.centralwidget)
        self.line_password_repeat.setGeometry(QtCore.QRect(210, 300, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_password_repeat.setFont(font)
        self.line_password_repeat.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_password_repeat.setObjectName("line_password_repeat")
        self.error_login = QtWidgets.QLabel(self.centralwidget)
        self.error_login.setGeometry(QtCore.QRect(280, 160, 301, 20))
        self.error_login.setStyleSheet("color: rgb(255, 0, 0);")
        self.error_login.setText("")
        self.error_login.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.error_login.setObjectName("error_login")
        self.error_password = QtWidgets.QLabel(self.centralwidget)
        self.error_password.setGeometry(QtCore.QRect(280, 220, 301, 20))
        self.error_password.setStyleSheet("color: rgb(255, 0, 0);")
        self.error_password.setText("")
        self.error_password.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.error_password.setObjectName("error_password")
        self.error_password_repeat = QtWidgets.QLabel(self.centralwidget)
        self.error_password_repeat.setGeometry(QtCore.QRect(410, 280, 171, 20))
        self.error_password_repeat.setStyleSheet("color: rgb(255, 0, 0);")
        self.error_password_repeat.setText("")
        self.error_password_repeat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.error_password_repeat.setObjectName("error_password_repeat")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.registration.setText(_translate("MainWindow", "Регистрация"))
        self.login.setText(_translate("MainWindow", "Логин:"))
        self.password.setText(_translate("MainWindow", "Пароль:"))
        self.signUp.setText(_translate("MainWindow", "Регистрация"))
        self.password_repeat.setText(_translate("MainWindow", "Подтвердите пароль:"))
